title = "Node Crypto Tracker Config"

[ticker]
  coins = ["ethereum","matic-network","litecoin","bitcoin","weth","celsius-degree-token","usd-coin"]
  vsCurrency = "cad" 
  refreshRate = 15

[aave]
  collateralInEth = 0.646
  borrowedInEth = 0.403
  borrowedInUsd = 904.34107
