title = "Node Crypto Tracker Config"

[ticker]
coins = [
  "litecoin",
  "bitcoin",
  "dogecoin",
  "matic-network",
  "ethereum",
  "weth",
  "usd-coin"
]
vsCurrency = "cad"
refreshRate = 16

[aave]
collateralInEth = 6
borrowedInEth = 4
borrowedInUsd = 7200
