title = "Node Crypto Tracker Config"

[ticker]
coins = [
  "litecoin",
  "bitcoin",
  "ethereum",
  "usd-coin",
  "matic-network",
  "dogecoin",
  "weth"
]
vsCurrency = "usd"
refreshRate = 16

[aave]
collateralInEth = 0.696
borrowedInEth = 0.403
borrowedInUsd = 904.34107
