title = "Node Crypto Tracker Config"

[ticker]
coins = [
  "litecoin",
  "bitcoin",
  "dogecoin",
  "matic-network",
  "ethereum",
  "weth",
  "usd-coin"
]
vsCurrency = "cad"
refreshRate = 16

[aave]
collateralInEth = 0.696
borrowedInEth = 0.403
borrowedInUsd = 904.34107
